baseurl = "https://housefresh.by/"
languageCode = "en-us"
title = "Продукты питания оптом в Минске: хлеб, сэндвичи, салаты, торты, выпечка, комплексные обеды | ХаусФреш"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "ХаусФреш"
	keywords = "замороженные продукты питания для кафе оптом, торты, выпечка, булочки для гамбургеров, багеты для сэндвичей, салаты, комплексные обеды от производителя оптом, мелкий опт, заморозка. Доставка обедов в офис. Минск, Беларусь"

	# The path must be relative to the static folder
	favicon = "img/houseFreshLogo.png"


	# Navigation
	[params.navigation]
		brand = "ХаусФреш"
		brandIcon = "img/houseFreshLogo.png"
		title = "ХаусФреш: продукты питания оптом, доставка обедов. Минск"

		[params.navigation.links]
			#about     = "О нас"
			#aboutTitle = "О компании ХаусФреш"
			aboutUrl = "/#about"
			catalog = "Продукция"
			catalogTitle = "Сэндвичи, булочки, чиабатта, салаты, выпечка, торты: цены, описание"
			catalogUrl = "/production"
			lunch  = "Обеды"
			lunchTitle = "Комплексные обеды, меню: описание, цены"
			lunchUrl = "/lunch"
			delivery  = "Доставка"
			deliveryTitle = "Условия доставки и оплаты"
			deliveryUrl = "/delivery"
			contact   = "Контакты"
			contactTitle = "Контакты ХаусФреш"
			contactUrl = "/#contact"


	# Hero section
	[params.hero]
		slogan     = "ХАУСФРЕШ | продукты питания оптом"
		companyIcon = "img/houseFreshLogo128x128.svg"	
		subtitle   = "[Мы предлагаем] (#services) оптовые и мелкооптовые поставки широкого ассортимента свежих и замороженных продуктов питания собственного производства: сэндвичи, булочки, багеты, чиабатта, хлеб, фаршированные мини багеты, салаты, выпечка, торты. Доставка обедов в офис и организация питания сотрудников на предприятиях!"
		buttonText = "Продукция"
		buttonTitle = "Сэндвичи, булочки, чиабатта, салаты, выпечка, торты, комплексные обеды: цены, описание"
		ButtonUrl = "production"


	# About section
	[params.about]
		headline    = "У нас есть то, что Вам нужно!"
		description = "Компания ХаусФреш существует на рынке продуктов питания совсем недавно, но уже успела завоевать популярность среди потребителей и зарекомендовать себя как надёжного партнёра. Мы нацелены на создание самых лучших продуктов питания (качество наших продуктов подтвержденно Декларациями ЕАЭС!), построение долгосрочных и надёжных отношений с нашими клиентами и партнёрами. Мы растём каждый день и готовы помочь нашим партнёрам расти вместе с нами! Мы приложим все усилия для эффективной совместной работы над общими целями. Присоединяйтесь к нам!" 
		subdescription = "Ищете, где в Минске купить оптом свежий или замороженный хлеб, багеты для сэндвичей, готовую выпечку, булочки, сэндвичи, вкусные торты, салаты для Вашего кафе, кофейни, ресторана или заказать комплексные обеды с доставкой в офис? <br> Посмотрите [каталог продукции ХаусФреш!] (https://housefresh.by/production) Свяжитесь с нами для получения более подробной информации об условиях заказа, оплаты и доставки продуктов питания и комплексных обедов."
		buttonText = "Связаться"
		buttonTitle = "Контакты ХаусФреш"

			
	# services section
	[params.services]
		#headline    = "К вашим услугам"
		#description = "[ХаусФреш](/) предлагает ... "
	[params.services.downloadButton]
			text = "Скачать каталог"
			link = "/files/HouseFresh.pdf"
	[params.services.contactButton]
			text = "Связаться"
			link = "/#contact"

	# ServiceTiles for product catalog
	  [params.ProdTile]
	    [[params.ProdTile.showcase]]
		  title = "Производство продуктов питания"
		  subtitle = "сэндвичи, булочки, чиабатта, салаты, выпечка, торты"
		  buttonTitle = "Каталог продукции: фото, описание, цены. ХаусФреш Минск"
		  image = "catalog/production-tile.jpg"
		  alt = "Производство продуктов питания, каталог ХаусФреш Минск Беларусь"
		  url = "production"
		  atitle = "Производство продуктов питания, каталог ХаусФреш"
	
	# ServiceTiles Section
	  [params.ServiceTiles]
		enable = true
		
		[[params.ServiceTiles.showcase]]
		  title = "Доставка"
		  subtitle = ""
		  image = "catalog/distribution-tile.jpg"
		  alt = "Доставка продуктов питания ХаусФреш Беларусь"
		  url = "delivery"
		  atitle = "Доставка продуктов питания ХаусФреш Беларусь"
		  

		[[params.ServiceTiles.showcase]]
		  title = "Комплексные обеды"
		  subtitle = ""
		  image = "catalog/canteen-tile.jpg"
		  alt = "Доставка обедов в офис. Минск Беларусь ХаусФреш"
		  url = "lunch"
		  atitle = "Комплексные обеды, меню: цены, описание | Минск"

		
    # Aside section
	[params.aside]
		headline = "Каталог продукции в формате PDF"

		[params.aside.button]
			text = "Скачать"
			link = "/files/HouseFresh.pdf"
			title = "Каталог продукции ХаусФреш: фото, описание, цены"
	
	
	# Partners section
	[params.partners]
		headline    = "Нам доверяют"
		description = " "
		
		
		
		[[params.partners.list]]
		logo = "perspective.jpg"
		alt = "партнёр Перспектива кофе логотип"
		#link = "#"
		
		[[params.partners.list]]
		logo = "yummy.svg"
		alt = "партнёр Yummy кафе логотип"
		#link = "#"
		
		[[params.partners.list]]
		logo = "Coffeecake.jpg"
		alt = "партнёр Coffeecake сеть кофеен на колёсах логотип"
		#link = "#"
		
	    

	# Contact section
	[params.contact]
		address = "220014, РБ, г.Минск, проспект Жукова, д.44, офис 1-4"
		phone = "+375293728006"
		phone2 = "+375445148090"
		phoneTitle = "телефон отдела продаж продуктов питания ХаусФреш"
		phoneDescription ="+375 29 372 80 06 (Дмитрий)"
		phoneDescription2 ="+375 44 514 80 90 (Роман)"
		email = "housefreshbysm@gmail.com"
		emailTitle = "e-mail отдела продаж продуктов питания ХаусФреш"
		emailDescription = "написать в ХаусФреш"
		
		companyIcon = "img/houseFreshLogo64x64.svg"	
		copyright = "© 2018 ХаусФреш, г.Минск, проспект Жукова, д.44, офис 1-4"
