baseurl = "https://housefresh.by/"
languageCode = "ru"
DefaultContentLanguage = "ru"
title = "Продукты оптом: сэндвичи, выпечка. Доставка обедов | ХаусФреш"
googleAnalytics = ""

[params]
	name = "ХаусФреш"
	keywords = "Продукты питания оптом: сэндвичи, торты, выпечка, Готовая продукция для кафе, Комплексные обеды, Корпоративное питание, Доставка обедов в офис"
	favicon = "img/houseFreshLogo.png"
	freeDeliveryCost = 80

	# Navigation
	[params.navigation]
		brand = "ХаусФреш"
		brandIcon = "img/houseFreshLogo.png"
		title = "ХаусФреш: продукты питания оптом, доставка обедов в офис. Минск"

		[params.navigation.links]
			catalog = "Продукция"
			catalogTitle = "Сэндвичи, Выпечка, Торты: фото, цены, описание | ХаусФреш"
			catalogUrl = "/production/"
			lunch  = "Обеды"
			lunchTitle = "Комплексные обеды, Доставка обедов в офис: цены, описание | ХаусФреш"
			lunchUrl = "/lunch/"
			delivery  = "Доставка"
			deliveryTitle = "Доставка обедов, Оптовые поставки продукции | ХаусФреш"
			deliveryUrl = "/delivery/"
			contact   = "Контакты"
			contactTitle = "Контакты | ХаусФреш"
			contactUrl = "#footer"
			cart   = "Корзина"
			cartTitle = "Перейти в корзину | ХаусФреш"
			cartUrl = "/#cart-modal"


	# Hero section
	[params.hero]
		slogan     = "ХАУСФРЕШ | Обеды <br>Продукты оптом"
		companyIcon = "img/houseFreshLogo128x128.svg"	
		subtitle   = "Мы предлагаем оптовые и мелкооптовые поставки широкого ассортимента свежих и замороженных продуктов питания собственного производства: сэндвичи, багеты, выпечка, торты, фаршированные мини багеты, салаты. <br>Доставка комплексных обедов в офис. Организация корпоративного питания сотрудников на предприятиях!"
		buttonText = "Продукция"
		buttonTitle = "Сэндвичи, булочки, чиабатта, салаты, выпечка, торты: цены, описание"


	# About section
	[params.lunchSection]
		headline    = "Вкусные комплексные обеды"
		description = "Большой выбор блюд <br>Индивидуальное меню <br>Организация корпоративного питания <br>Обновление обеденного меню каждый день <br>Розничная точка 'ОбедБуфет' на Жукова 44 (второй этаж) <br>Бесплатная доставка обедов в офис <br>Доступные цены"
		lunchButtonText = "Заказать обед"
		lunchButtonTitle = "Заказать комплексный обед с доставкой в офис | ХаусФреш"
		lunchButtonLink = "/lunch/"
	[params.productionSection]
		headline    = "Мелкооптовые поставки продукции собственного производства"
		description = "Большой выбор продуктов питания: свежий и замороженный хлеб, багеты, булочки, чиабатта, сэндвичи, багеты для сэндвичей, булочки для гамбургеров, свежая выпечка, вкусные торты, салаты для кафе, кофейни, ресторана."
		subdescription = "Опт и Мелкий опт от 35руб. <br>Выгодные индивидуальные условия <br>Качество, подтверждённое Декларациями ЕАЭС   <br>Быстрое исполнение заявки от 1дня! <br>Доставка по Минску"
		productionButtonText = "Наша продукция"
		productionButtonTitle = "Сэндвичи, Выпечка, Торты, Мелкий опт | ХаусФреш"
		productionButtonLink = "/production/"

		
	# Partners section
	[params.partners]
		[[params.partners.list]]
		logo = "perspective.jpg"
		alt = "Перспектива кофе логотип"
		
		[[params.partners.list]]
		logo = "yummy.svg"
		alt = "Yummy кафе логотип"
		
		[[params.partners.list]]
		logo = "Coffeecake.jpg"
		alt = "Coffeecake сеть кофеен на колёсах логотип"
		
		[[params.partners.list]]
		logo = "свежаежа лого.jpg"
		alt = "СвежаЕжа буфет логотип"
	    

	# Contact section
	[params.contact]
		address = "220014, РБ, г.Минск, проспект Жукова, д.44, офис 1-4"
		addressTitle = "Показать адрес ХаусФреш на карте"
		phone = "+375293728006"
		phone2 = "+375445148090"
		phoneTitle = "Позвонить в отдел продаж продуктов питания ХаусФреш"
		phoneDescription ="+375 29 372 80 06"
		phoneDescription2 ="+375 44 514 80 90"
		orderEmail = "housefreshbysm@gmail.com"
		workingHours = "будние дни с 9.00 до 18.00"
				
		companyIcon = "img/houseFreshLogo64x64.svg"	
		copyrightMain = "© ХаусФреш 2018 | Все права защищены."
		copyrightDescription = "Копирование и использование материалов данного сайта разрешено только по согласованию с владельцем."