baseurl = "https://housefresh.by/"
languageCode = "ru"
DefaultContentLanguage = "ru"
title = "–°—ç–Ω–¥–≤–∏—á–∏, –í—ã–ø–µ—á–∫–∞ (–ú–µ–ª–∫–∏–π –û–ø—Ç). ü•ó –î–æ—Å—Ç–∞–≤–∫–∞ –û–±–µ–¥–æ–≤ | –•–∞—É—Å–§—Ä–µ—à"
googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
	name = "–•–∞—É—Å–§—Ä–µ—à"
	favicon = "img/houseFreshLogo.png"
	freeDeliveryCost = 80
	wholesalePriceThreshold = 35

	# Navigation
	[params.navigation]
		brand = "–•–∞—É—Å–§—Ä–µ—à"
		brandIcon = "img/houseFreshLogo.png"
		title = "–°—ç–Ω–¥–≤–∏—á–∏, –í—ã–ø–µ—á–∫–∞ (–ú–µ–ª–∫–∏–π –û–ø—Ç). ü•ó –î–æ—Å—Ç–∞–≤–∫–∞ –û–±–µ–¥–æ–≤ | –•–∞—É—Å–§—Ä–µ—à –ú–∏–Ω—Å–∫"

		[params.navigation.links]
			catalog = "–ü—Ä–æ–¥—É–∫—Ü–∏—è"
			catalogTitle = "–û–ø—Ç–æ–≤–∞—è –ø—Ä–æ–¥—É–∫—Ü–∏—è, –æ–ø–∏—Å–∞–Ω–∏–µ, —Ü–µ–Ω—ã –¥–ª—è –∫–∞—Ñ–µ: –°—ç–Ω–¥–≤–∏—á–∏, –í—ã–ø–µ—á–∫–∞, –¢–æ—Ä—Ç—ã | –•–∞—É—Å–§—Ä–µ—à"
			catalogUrl = "/production/"
			lunch  = "–û–ë–ï–î –ë–£–§–ï–¢"
			lunchTitle = "–ö–∞—Ñ–µ –¥–æ–º–∞—à–Ω–µ–π –∫—É—Ö–Ω–∏ –û–ë–ï–î –ë–£–§–ï–¢: –∞–¥—Ä–µ—Å, —Ä–µ–∂–∏–º —Ä–∞–±–æ—Ç—ã. –ö–æ–º–ø–ª–µ–∫—Å–Ω—ã–µ –û–±–µ–¥—ã —Å –¥–æ—Å—Ç–∞–≤–∫–æ–π –≤ –û—Ñ–∏—Å –∏ –Ω–∞ –î–æ–º."
			lunchUrl = "/lunch/"
			delivery  = "–î–æ—Å—Ç–∞–≤–∫–∞"
			deliveryTitle = "–î–æ—Å—Ç–∞–≤–∫–∞ –æ–±–µ–¥–æ–≤, –û–ø—Ç–æ–≤—ã–µ –ø–æ—Å—Ç–∞–≤–∫–∏ –ø—Ä–æ–¥—É–∫—Ü–∏–∏ | –•–∞—É—Å–§—Ä–µ—à"
			deliveryUrl = "/delivery/"
			contact   = "–ö–æ–Ω—Ç–∞–∫—Ç—ã"
			contactTitle = "–ö–æ–Ω—Ç–∞–∫—Ç—ã | –•–∞—É—Å–§—Ä–µ—à"
			contactUrl = "#footer"
			cart   = "–ö–æ—Ä–∑–∏–Ω–∞"
			cartTitle = "–ü–µ—Ä–µ–π—Ç–∏ –≤ –∫–æ—Ä–∑–∏–Ω—É | –•–∞—É—Å–§—Ä–µ—à"
			cartUrl = "/#cart-modal"


	# Hero section
	[params.hero]
		slogan     = "–•–ê–£–°–§–†–ï–® | –û–±–µ–¥—ã <br>–ü—Ä–æ–¥—É–∫—Ç—ã –æ–ø—Ç–æ–º"
		companyIcon = "img/houseFreshLogo128x128.svg"	
		subtitle   = "–û–ø—Ç–æ–≤—ã–µ –∏ –º–µ–ª–∫–æ–æ–ø—Ç–æ–≤—ã–µ (–æ—Ç 35—Ä—É–±) –ø–æ—Å—Ç–∞–≤–∫–∏ —Å–≤–µ–∂–∏—Ö –∏ –∑–∞–º–æ—Ä–æ–∂–µ–Ω–Ω—ã—Ö –ø—Ä–æ–¥—É–∫—Ç–æ–≤ –ø–∏—Ç–∞–Ω–∏—è —Å–æ–±—Å—Ç–≤–µ–Ω–Ω–æ–≥–æ –ø—Ä–æ–∏–∑–≤–æ–¥—Å—Ç–≤–∞: –°—ç–Ω–¥–≤–∏—á–∏, –ë–∞–≥–µ—Ç—ã, –í—ã–ø–µ—á–∫–∞, –¢–æ—Ä—Ç—ã, –°–∞–ª–∞—Ç—ã. <br> –†–∞–±–æ—Ç–∞–µ—Ç –Ω–∞—à–µ –∫–∞—Ñ–µ –¥–æ–º–∞—à–Ω–µ–π –∫—É—Ö–Ω–∏ <b><a class='header-link' href='/lunch' title='–ö–∞—Ñ–µ –û–ë–ï–î –ë–£–§–ï–¢: –∞–¥—Ä–µ—Å, —Ä–µ–∂–∏–º —Ä–∞–±–æ—Ç—ã. –û–±–µ–¥–µ–Ω–Ω–æ–µ –º–µ–Ω—é: –æ–ø–∏—Å–∞–Ω–∏–µ, —Ü–µ–Ω—ã.'>–û–ë–ï–î –ë–£–§–ï–¢</a></b> –Ω–∞ –ñ—É–∫–æ–≤–∞ 44 (–≤—Ç–æ—Ä–æ–π —ç—Ç–∞–∂). –î–æ—Å—Ç–∞–≤–∫–∞ –¥–æ–º–∞—à–Ω–∏—Ö –∫–æ–º–ø–ª–µ–∫—Å–Ω—ã—Ö –æ–±–µ–¥–æ–≤ –≤ –æ—Ñ–∏—Å. –û—Ä–≥–∞–Ω–∏–∑–∞—Ü–∏—è –∫–æ—Ä–ø–æ—Ä–∞—Ç–∏–≤–Ω–æ–≥–æ –ø–∏—Ç–∞–Ω–∏—è!"
		buttonText = "–ù–∞—à–∞ –ø—Ä–æ–¥—É–∫—Ü–∏—è"
		buttonTitle = "–û–ø—Ç–æ–≤–∞—è –ø—Ä–æ–¥—É–∫—Ü–∏—è, –æ–ø–∏—Å–∞–Ω–∏–µ, –æ–ø—Ç–æ–≤—ã–µ —Ü–µ–Ω—ã –¥–ª—è –∫–∞—Ñ–µ: –°—ç–Ω–¥–≤–∏—á–∏, –í—ã–ø–µ—á–∫–∞, –¢–æ—Ä—Ç—ã, –ú–µ–ª–∫–∏–π –æ–ø—Ç | –•–∞—É—Å–§—Ä–µ—à –ú–∏–Ω—Å–∫"
		

	# About section
	[params.lunchSection]
		headline    = "–î–æ—Å—Ç–∞–≤–∫–∞ –≥–æ—Ä—è—á–∏—Ö –∫–æ–º–ø–ª–µ–∫—Å–Ω—ã—Ö –æ–±–µ–¥–æ–≤ –≤ –æ—Ñ–∏—Å"
		description = "–∏–∑ –Ω–∞—à–µ–≥–æ –∫–∞—Ñ–µ –¥–æ–º–∞—à–Ω–µ–π –∫—É—Ö–Ω–∏ <b><a class='header-link' href='/lunch' title='–ö–∞—Ñ–µ –û–ë–ï–î –ë–£–§–ï–¢: –∞–¥—Ä–µ—Å, —Ä–µ–∂–∏–º —Ä–∞–±–æ—Ç—ã. –û–±–µ–¥–µ–Ω–Ω–æ–µ –º–µ–Ω—é: –æ–ø–∏—Å–∞–Ω–∏–µ, —Ü–µ–Ω—ã.'>–û–ë–ï–î –ë–£–§–ï–¢</a></b> –Ω–∞ –ñ—É–∫–æ–≤–∞ 44. <br>–ó–∞–∫–∞–∑ '–Ω–∞ —Å–µ–≥–æ–¥–Ω—è' –¥–æ–ª–∂–µ–Ω –±—ã—Ç—å –æ—Ñ–æ—Ä–º–ª–µ–Ω —á–µ—Ä–µ–∑ –∫–æ—Ä–∑–∏–Ω—É —Å–∞–π—Ç–∞ –∏–ª–∏ –ø–æ —É–∫–∞–∑–∞–Ω–Ω—ã–º –≤ –∫–æ–Ω—Ç–∞–∫—Ç–∞—Ö —Ç–µ–ª–µ—Ñ–æ–Ω–∞–º <b>–¥–æ 11.00</b> —Ç–µ–∫—É—â–µ–≥–æ –¥–Ω—è. <br>–î–æ—Å—Ç–∞–≤–∫–∞ –≤ –æ—Ñ–∏—Å –≤—ã–ø–æ–ª–Ω—è–µ—Ç—Å—è —Ç–æ–ª—å–∫–æ –ø–æ –±—É–¥–Ω—è–º."
		subdescription = "–ò–Ω–¥–∏–≤–∏–¥—É–∞–ª—å–Ω–æ–µ –º–µ–Ω—é <br> –û—Ä–≥–∞–Ω–∏–∑–∞—Ü–∏—è –∫–æ—Ä–ø–æ—Ä–∞—Ç–∏–≤–Ω–æ–≥–æ –ø–∏—Ç–∞–Ω–∏—è <br> –û–±–Ω–æ–≤–ª–µ–Ω–∏–µ –æ–±–µ–¥–µ–Ω–Ω–æ–≥–æ –º–µ–Ω—é –∫–∞–∂–¥—ã–π –¥–µ–Ω—å <br>–ë–æ–ª—å—à–æ–π –≤—ã–±–æ—Ä: —Å–∞–ª–∞—Ç—ã, —Å—É–ø—ã, –≥–æ—Ä—è—á–µ–µ, –≥–∞—Ä–Ω–∏—Ä—ã, –Ω–∞–ø–∏—Ç–∫–∏, –≤—ã–ø–µ—á–∫–∞ <br>–ë–µ—Å–ø–ª–∞—Ç–Ω–∞—è –¥–æ—Å—Ç–∞–≤–∫–∞ –æ–±–µ–¥–æ–≤ –≤ –æ—Ñ–∏—Å –∏ –Ω–∞ –¥–æ–º <br>–û–±—Å–ª—É–∂–∏–≤–∞–Ω–∏–µ —Å—Ç–æ–ª–æ–≤—ã—Ö –∏ –∫–∞—Ñ–µ <br>–ö–µ–π—Ç–µ—Ä–∏–Ω–≥ <br>–î–æ—Å—Ç—É–ø–Ω—ã–µ —Ü–µ–Ω—ã"
		lunchButtonText = "–ó–∞–∫–∞–∑–∞—Ç—å –æ–±–µ–¥"
		lunchButtonTitle = "–ú–µ–Ω—é –∏ —Å—Ç–æ–∏–º–æ—Å—Ç—å –∫–æ–º–ø–ª–µ–∫—Å–Ω—ã—Ö –æ–±–µ–¥–æ–≤ —Å –¥–æ—Å—Ç–∞–≤–∫–æ–π –≤ –æ—Ñ–∏—Å | –•–∞—É—Å–§—Ä–µ—à –ú–∏–Ω—Å–∫"
		lunchButtonLink = "/lunch/"
	[params.productionSection]
		headline    = "–ú–µ–ª–∫–æ–æ–ø—Ç–æ–≤—ã–µ –ø–æ—Å—Ç–∞–≤–∫–∏ –ø—Ä–æ–¥—É–∫—Ü–∏–∏ —Å–æ–±—Å—Ç–≤–µ–Ω–Ω–æ–≥–æ –ø—Ä–æ–∏–∑–≤–æ–¥—Å—Ç–≤–∞"
		description = "–ë–æ–ª—å—à–æ–π –≤—ã–±–æ—Ä <strong>–≥–æ—Ç–æ–≤–æ–π –ø—Ä–æ–¥—É–∫—Ü–∏–∏ –æ–ø—Ç–æ–º</strong>: <br> —Å–≤–µ–∂–∏–π –∏ –∑–∞–º–æ—Ä–æ–∂–µ–Ω–Ω—ã–π –•–ª–µ–±, –ë–∞–≥–µ—Ç—ã, –ë—É–ª–æ—á–∫–∏, –ß–∏–∞–±–∞—Ç—Ç–∞, –°—ç–Ω–¥–≤–∏—á–∏ –∏–∑ –±–∞–≥–µ—Ç–∞, –ë—É–ª–æ—á–∫–∏ –¥–ª—è –≥–∞–º–±—É—Ä–≥–µ—Ä–æ–≤, –ë–∞–≥–µ—Ç—ã –¥–ª—è —Å—ç–Ω–¥–≤–∏—á–µ–π –∏ —Ö–æ—Ç –¥–æ–≥–æ–≤, –ë—É–ª–æ—á–∫–∏ –¥–ª—è —Ö–ª–µ–±–Ω–æ–π –∫–æ—Ä–∑–∏–Ω—ã, –í—ã–ø–µ—á–∫–∞, –°–ª–æ–π–∫–∏, –ö—Ä—É–∞—Å—Å–∞–Ω—ã, –ú–∞—Ñ—Ñ–∏–Ω—ã, –≤–∫—É—Å–Ω—ã–µ –¢–æ—Ä—Ç—ã, –¢–æ—Ä—Ç—ã –≤ —Å—Ç–∞–∫–∞–Ω–µ, —Å–≤–µ–∂–∏–µ –°–∞–ª–∞—Ç—ã, –≥–æ—Ä—è—á–∏–µ –ö–æ–º–ø–ª–µ–∫—Å–Ω—ã–µ –û–±–µ–¥—ã –æ–ø—Ç–æ–º –¥–ª—è –∫–∞—Ñ–µ, –∫–æ—Ñ–µ–π–Ω–∏, –±–∏—Å—Ç—Ä–æ, —Å—Ç–æ–ª–æ–≤–æ–π, —Ä–µ—Å—Ç–æ—Ä–∞–Ω–∞, —à–∫–æ–ª, –±–∏–∑–Ω–µ—Å-—Ü–µ–Ω—Ç—Ä–æ–≤ –∏ –æ—Ñ–∏—Å–æ–≤. <br> <br>–í–æ–∑–º–æ–∂–Ω–æ –∏–∑–≥–æ—Ç–æ–≤–ª–µ–Ω–∏–µ <strong>–æ–ø—Ç–æ–≤–æ–π –ø—Ä–æ–¥—É–∫—Ü–∏–∏ <a class='header-link' href='/production/#on-order' title='–ü—Ä–æ–¥—É–∫—Ü–∏—è –Ω–∞ –∑–∞–∫–∞–∑: –¢–æ—Ä—Ç—ã, –í—ã–ø–µ—á–∫–∞, –°—ç–Ω–¥–≤–∏—á–∏, –ë—É—Ç–µ—Ä–±—Ä–æ–¥—ã'> –Ω–∞ –∑–∞–∫–∞–∑</a></strong>: –¢–æ—Ä—Ç—ã, –í—ã–ø–µ—á–∫–∞, –°—ç–Ω–¥–≤–∏—á–∏ –∏–∑ –±–∞–≥–µ—Ç–∞, –ë—É—Ç–µ—Ä–±—Ä–æ–¥—ã –∏ —Ç.–¥."
		subdescription = "–¶–µ–Ω—ã –ø—Ä–æ–∏–∑–≤–æ–¥–∏—Ç–µ–ª—è <br>–û–ø—Ç –∏ –ú–µ–ª–∫–∏–π –æ–ø—Ç –æ—Ç 35—Ä—É–±. <br>–í—ã–≥–æ–¥–Ω—ã–µ –∏–Ω–¥–∏–≤–∏–¥—É–∞–ª—å–Ω—ã–µ —É—Å–ª–æ–≤–∏—è <br>–ö–∞—á–µ—Å—Ç–≤–æ, –ø–æ–¥—Ç–≤–µ—Ä–∂–¥—ë–Ω–Ω–æ–µ –î–µ–∫–ª–∞—Ä–∞—Ü–∏—è–º–∏ –ï–ê–≠–° <br>–î–æ—Å—Ç–∞–≤–∫–∞ –°—ç–Ω–¥–≤–∏—á–µ–π, –í—ã–ø–µ—á–∫–∏, –¢–æ—Ä—Ç–æ–≤ –≤ –∫–∞—Ñ–µ –ú–∏–Ω—Å–∫–∞ <br> –í–æ–∑–º–æ–∂–Ω–∞ –¥–æ—Å—Ç–∞–≤–∫–∞ –ø–æ –ú–∏–Ω—Å–∫–æ–º—É —Ä–∞–π–æ–Ω—É –∏ –≤—Å–µ–π –ë–µ–ª–∞—Ä—É—Å–∏  <br> –ì–æ—Ç–æ–≤–∞—è –°–≤–µ–∂–∞—è –∏ –ó–∞–º–æ—Ä–æ–∂–µ–Ω–Ω–∞—è –ø—Ä–æ–¥—É–∫—Ü–∏—è <br>–ë—ã—Å—Ç—Ä–æ–µ –∏—Å–ø–æ–ª–Ω–µ–Ω–∏–µ –∑–∞—è–≤–∫–∏ –æ—Ç 1–¥–Ω—è! <br> –¢–æ—Ä—Ç—ã, –í—ã–ø–µ—á–∫–∞, –•–ª–µ–± –Ω–∞ –∑–∞–∫–∞–∑"
		productionButtonText = "–ù–∞—à–∞ –ø—Ä–æ–¥—É–∫—Ü–∏—è"
		productionButtonTitle = "–û–ø–∏—Å–∞–Ω–∏–µ –∏ —Å—Ç–æ–∏–º–æ—Å—Ç—å –ø—Ä–æ–¥—É–∫—Ü–∏–∏ –æ–ø—Ç–æ–º: –°—ç–Ω–¥–≤–∏—á–∏, –í—ã–ø–µ—á–∫–∞, –¢–æ—Ä—Ç—ã, –ú–µ–ª–∫–∏–π –æ–ø—Ç | –•–∞—É—Å–§—Ä–µ—à –ú–∏–Ω—Å–∫"
		productionButtonLink = "/production/"

		
	# Partners section
	[params.partners]
		[[params.partners.list]]
		logo = "—Å–µ—Ç—å-–∫–æ—Ñ–µ–µ–Ω-–ü–µ—Ä—Å–ø–µ–∫—Ç–∏–≤–∞-–ú–∏–Ω—Å–∫-–ª–æ–≥–æ.jpg"
		alt = "–ü–µ—Ä—Å–ø–µ–∫—Ç–∏–≤–∞ –∫–æ—Ñ–µ –ª–æ–≥–æ—Ç–∏–ø"
		
		[[params.partners.list]]
		logo = "—Å–µ—Ç—å-–∫–∞—Ñ–µ-Yummy-–ú–∏–Ω—Å–∫-–ª–æ–≥–æ.svg"
		alt = "Yummy –∫–∞—Ñ–µ –ª–æ–≥–æ—Ç–∏–ø"
		
		[[params.partners.list]]
		logo = "—Å–µ—Ç—å-–∫–æ—Ñ–µ–µ–Ω-–Ω–∞-–∫–æ–ª—ë—Å–∞—Ö-Coffeecake-–ú–∏–Ω—Å–∫-–ª–æ–≥–æ.jpg"
		alt = "Coffeecake —Å–µ—Ç—å –∫–æ—Ñ–µ–µ–Ω –Ω–∞ –∫–æ–ª—ë—Å–∞—Ö –ª–æ–≥–æ—Ç–∏–ø"
		
		[[params.partners.list]]
		logo = "–±—É—Ñ–µ—Ç-–°–≤–µ–∂–∞–µ–∂–∞-–ú–∏–Ω—Å–∫-–ª–æ–≥–æ.jpg"
		alt = "–°–≤–µ–∂–∞–ï–∂–∞ –±—É—Ñ–µ—Ç –ª–æ–≥–æ—Ç–∏–ø"
		
		[[params.partners.list]]
		logo = "–∫–∞—Ñ–µ-–±–∏—Å—Ç—Ä–æ-–æ–±–µ–¥-–±—É—Ñ–µ—Ç-–ú–∏–Ω—Å–∫-–ª–æ–≥–æ.svg"
		alt = "–ö–∞—Ñ–µ-–±–∏—Å—Ç—Ä–æ '–û–±–µ–¥ –ë—É—Ñ–µ—Ç' –ú–∏–Ω—Å–∫ –ª–æ–≥–æ—Ç–∏–ø"
	    

	# Contact section
	[params.contact]
		address = "220014, –†–ë, –≥.–ú–∏–Ω—Å–∫, –ø—Ä–æ—Å–ø–µ–∫—Ç –ñ—É–∫–æ–≤–∞, –¥.44, –æ—Ñ–∏—Å 1-4"
		addressTitle = "–ü–æ–∫–∞–∑–∞—Ç—å –∞–¥—Ä–µ—Å –•–∞—É—Å–§—Ä–µ—à –Ω–∞ –∫–∞—Ä—Ç–µ"
		phone = "+375293728006"
		phone2 = "+375445148090"
		phoneTitle = "–ü–æ–∑–≤–æ–Ω–∏—Ç—å –≤ –æ—Ç–¥–µ–ª –æ–ø—Ç–æ–≤—ã—Ö –ø—Ä–æ–¥–∞–∂ –≥–æ—Ç–æ–≤–æ–π –ø—Ä–æ–¥—É–∫—Ü–∏–∏ –•–∞—É—Å–§—Ä–µ—à"
		phoneDescription ="+375 29 372 80 06"
		phoneDescription2 ="+375 44 514 80 90"
		orderEmail = "housefreshbysm@gmail.com"
		workingHours = "–±—É–¥–Ω–∏–µ –¥–Ω–∏ —Å 9.00 –¥–æ 18.00"
				
		companyIcon = "img/houseFreshLogo64x64.svg"	
		copyrightMain = "¬© –•–∞—É—Å–§—Ä–µ—à 2018 | –í—Å–µ –ø—Ä–∞–≤–∞ –∑–∞—â–∏—â–µ–Ω—ã"
		copyrightDescription = "–ö–æ–ø–∏—Ä–æ–≤–∞–Ω–∏–µ –∏ –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏–µ –º–∞—Ç–µ—Ä–∏–∞–ª–æ–≤ –¥–∞–Ω–Ω–æ–≥–æ —Å–∞–π—Ç–∞ —Ä–∞–∑—Ä–µ—à–µ–Ω–æ —Ç–æ–ª—å–∫–æ –ø–æ —Å–æ–≥–ª–∞—Å–æ–≤–∞–Ω–∏—é —Å –≤–ª–∞–¥–µ–ª—å—Ü–µ–º."