baseurl = "https://housefresh.by/"
languageCode = "ru"
DefaultContentLanguage = "ru"
title = "–°—ç–Ω–¥–≤–∏—á–∏, –í—ã–ø–µ—á–∫–∞ (–ú–µ–ª–∫–∏–π –û–ø—Ç). ü•ó –î–æ—Å—Ç–∞–≤–∫–∞ –û–±–µ–¥–æ–≤ | –•–∞—É—Å–§—Ä–µ—à"
googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
	name = "–•–∞—É—Å–§—Ä–µ—à"
	favicon = "img/houseFreshLogo.png"
	freeDeliveryCost = 80

	# Navigation
	[params.navigation]
		brand = "–•–∞—É—Å–§—Ä–µ—à"
		brandIcon = "img/houseFreshLogo.png"
		title = "–°—ç–Ω–¥–≤–∏—á–∏, –í—ã–ø–µ—á–∫–∞ (–ú–µ–ª–∫–∏–π –û–ø—Ç). ü•ó –î–æ—Å—Ç–∞–≤–∫–∞ –û–±–µ–¥–æ–≤ | –•–∞—É—Å–§—Ä–µ—à –ú–∏–Ω—Å–∫"

		[params.navigation.links]
			catalog = "–ü—Ä–æ–¥—É–∫—Ü–∏—è"
			catalogTitle = "–û–ø–∏—Å–∞–Ω–∏–µ –∏ —Ü–µ–Ω—ã –Ω–∞ –≥–æ—Ç–æ–≤—É—é –ø—Ä–æ–¥—É–∫—Ü–∏—é –¥–ª—è –∫–∞—Ñ–µ: –°—ç–Ω–¥–≤–∏—á–∏, –í—ã–ø–µ—á–∫–∞, –¢–æ—Ä—Ç—ã | –•–∞—É—Å–§—Ä–µ—à"
			catalogUrl = "/production/"
			lunch  = "–û–ë–ï–î –ë–£–§–ï–¢"
			lunchTitle = "–ö–∞—Ñ–µ –û–ë–ï–î –ë–£–§–ï–¢: –∞–¥—Ä–µ—Å, —Ä–µ–∂–∏–º —Ä–∞–±–æ—Ç—ã. –ö–æ–º–ø–ª–µ–∫—Å–Ω—ã–µ –û–±–µ–¥—ã —Å –¥–æ—Å—Ç–∞–≤–∫–æ–π –≤ –û—Ñ–∏—Å –∏ –Ω–∞ –î–æ–º."
			lunchUrl = "/lunch/"
			delivery  = "–î–æ—Å—Ç–∞–≤–∫–∞"
			deliveryTitle = "–î–æ—Å—Ç–∞–≤–∫–∞ –æ–±–µ–¥–æ–≤, –û–ø—Ç–æ–≤—ã–µ –ø–æ—Å—Ç–∞–≤–∫–∏ –ø—Ä–æ–¥—É–∫—Ü–∏–∏ | –•–∞—É—Å–§—Ä–µ—à"
			deliveryUrl = "/delivery/"
			contact   = "–ö–æ–Ω—Ç–∞–∫—Ç—ã"
			contactTitle = "–ö–æ–Ω—Ç–∞–∫—Ç—ã | –•–∞—É—Å–§—Ä–µ—à"
			contactUrl = "#footer"
			cart   = "–ö–æ—Ä–∑–∏–Ω–∞"
			cartTitle = "–ü–µ—Ä–µ–π—Ç–∏ –≤ –∫–æ—Ä–∑–∏–Ω—É | –•–∞—É—Å–§—Ä–µ—à"
			cartUrl = "/#cart-modal"


	# Hero section
	[params.hero]
		slogan     = "–•–ê–£–°–§–†–ï–® | –û–±–µ–¥—ã <br>–ü—Ä–æ–¥—É–∫—Ç—ã –æ–ø—Ç–æ–º"
		companyIcon = "img/houseFreshLogo128x128.svg"	
		subtitle   = "–û–ø—Ç–æ–≤—ã–µ –∏ –º–µ–ª–∫–æ–æ–ø—Ç–æ–≤—ã–µ –ø–æ—Å—Ç–∞–≤–∫–∏ —Å–≤–µ–∂–∏—Ö –∏ –∑–∞–º–æ—Ä–æ–∂–µ–Ω–Ω—ã—Ö –ø—Ä–æ–¥—É–∫—Ç–æ–≤ –ø–∏—Ç–∞–Ω–∏—è —Å–æ–±—Å—Ç–≤–µ–Ω–Ω–æ–≥–æ –ø—Ä–æ–∏–∑–≤–æ–¥—Å—Ç–≤–∞: –°—ç–Ω–¥–≤–∏—á–∏, –ë–∞–≥–µ—Ç—ã, –í—ã–ø–µ—á–∫–∞, –¢–æ—Ä—Ç—ã, –°–∞–ª–∞—Ç—ã. <br> –†–∞–±–æ—Ç–∞–µ—Ç –Ω–∞—à–µ –∫–∞—Ñ–µ <b><a class='header-link' href='/lunch' title='–ö–∞—Ñ–µ –û–ë–ï–î –ë–£–§–ï–¢: –∞–¥—Ä–µ—Å, —Ä–µ–∂–∏–º —Ä–∞–±–æ—Ç—ã. –û–±–µ–¥–µ–Ω–Ω–æ–µ –º–µ–Ω—é: –æ–ø–∏—Å–∞–Ω–∏–µ, —Ü–µ–Ω—ã.'>–û–ë–ï–î –ë–£–§–ï–¢</a></b> –Ω–∞ –ñ—É–∫–æ–≤–∞ 44 (–≤—Ç–æ—Ä–æ–π —ç—Ç–∞–∂). –î–æ—Å—Ç–∞–≤–∫–∞ –¥–æ–º–∞—à–Ω–∏—Ö –∫–æ–º–ø–ª–µ–∫—Å–Ω—ã—Ö –æ–±–µ–¥–æ–≤ –≤ –æ—Ñ–∏—Å —Å–æ —Å–∫–∏–¥–∫–æ–π. –û—Ä–≥–∞–Ω–∏–∑–∞—Ü–∏—è –∫–æ—Ä–ø–æ—Ä–∞—Ç–∏–≤–Ω–æ–≥–æ –ø–∏—Ç–∞–Ω–∏—è!"
		buttonText = "–ù–∞—à–∞ –ø—Ä–æ–¥—É–∫—Ü–∏—è"
		buttonTitle = "–û–ø–∏—Å–∞–Ω–∏–µ –∏ —Å—Ç–æ–∏–º–æ—Å—Ç—å –ø—Ä–æ–¥—É–∫—Ü–∏–∏: –°—ç–Ω–¥–≤–∏—á–∏, –í—ã–ø–µ—á–∫–∞, –¢–æ—Ä—Ç—ã, –ú–µ–ª–∫–∏–π –æ–ø—Ç | –•–∞—É—Å–§—Ä–µ—à –ú–∏–Ω—Å–∫"
		

	# About section
	[params.lunchSection]
		headline    = "–î–æ—Å—Ç–∞–≤–∫–∞ –¥–æ–º–∞—à–Ω–∏—Ö –∫–æ–º–ø–ª–µ–∫—Å–Ω—ã—Ö –æ–±–µ–¥–æ–≤"
		description = "–ë–æ–ª—å—à–æ–π –≤—ã–±–æ—Ä –±–ª—é–¥ <br>–ò–Ω–¥–∏–≤–∏–¥—É–∞–ª—å–Ω–æ–µ –º–µ–Ω—é <br>–û—Ä–≥–∞–Ω–∏–∑–∞—Ü–∏—è –∫–æ—Ä–ø–æ—Ä–∞—Ç–∏–≤–Ω–æ–≥–æ –ø–∏—Ç–∞–Ω–∏—è <br>–û–±–Ω–æ–≤–ª–µ–Ω–∏–µ –æ–±–µ–¥–µ–Ω–Ω–æ–≥–æ –º–µ–Ω—é –∫–∞–∂–¥—ã–π –¥–µ–Ω—å  <br>–°–∫–∏–¥–∫–∞ 10% –ø—Ä–∏ –∑–∞–∫–∞–∑–µ –æ–±–µ–¥–∞ —Å –¥–æ—Å—Ç–∞–≤–∫–æ–π –≤ –æ—Ñ–∏—Å –∏–ª–∏ –Ω–∞–≤—ã–Ω–æ—Å <br>–ö–∞—Ñ–µ <b><a class='header-link' href='/lunch' title='–ö–∞—Ñ–µ –û–ë–ï–î –ë–£–§–ï–¢: –∞–¥—Ä–µ—Å, —Ä–µ–∂–∏–º —Ä–∞–±–æ—Ç—ã. –û–±–µ–¥–µ–Ω–Ω–æ–µ –º–µ–Ω—é: –æ–ø–∏—Å–∞–Ω–∏–µ, —Ü–µ–Ω—ã.'>–û–ë–ï–î –ë–£–§–ï–¢</a></b> –Ω–∞ –ñ—É–∫–æ–≤–∞ 44 (–≤—Ç–æ—Ä–æ–π —ç—Ç–∞–∂) <br>–ë–µ—Å–ø–ª–∞—Ç–Ω–∞—è –¥–æ—Å—Ç–∞–≤–∫–∞ –æ–±–µ–¥–æ–≤ –≤ –æ—Ñ–∏—Å/–Ω–∞ –¥–æ–º <br>–û–±—Å–ª—É–∂–∏–≤–∞–Ω–∏–µ —Å—Ç–æ–ª–æ–≤—ã—Ö –∏ –∫–∞—Ñ–µ <br>–ö–µ–π—Ç–µ—Ä–∏–Ω–≥ <br>–î–æ—Å—Ç—É–ø–Ω—ã–µ —Ü–µ–Ω—ã"
		lunchButtonText = "–ó–∞–∫–∞–∑–∞—Ç—å –æ–±–µ–¥"
		lunchButtonTitle = "–ú–µ–Ω—é –∏ —Å—Ç–æ–∏–º–æ—Å—Ç—å –∫–æ–º–ø–ª–µ–∫—Å–Ω—ã—Ö –æ–±–µ–¥–æ–≤ —Å –¥–æ—Å—Ç–∞–≤–∫–æ–π –≤ –æ—Ñ–∏—Å | –•–∞—É—Å–§—Ä–µ—à –ú–∏–Ω—Å–∫"
		lunchButtonLink = "/lunch/"
	[params.productionSection]
		headline    = "–ú–µ–ª–∫–æ–æ–ø—Ç–æ–≤—ã–µ –ø–æ—Å—Ç–∞–≤–∫–∏ –ø—Ä–æ–¥—É–∫—Ü–∏–∏ —Å–æ–±—Å—Ç–≤–µ–Ω–Ω–æ–≥–æ –ø—Ä–æ–∏–∑–≤–æ–¥—Å—Ç–≤–∞"
		description = "–ë–æ–ª—å—à–æ–π –≤—ã–±–æ—Ä –≥–æ—Ç–æ–≤–æ–π –ø—Ä–æ–¥—É–∫—Ü–∏–∏: —Å–≤–µ–∂–∏–π –∏ –∑–∞–º–æ—Ä–æ–∂–µ–Ω–Ω—ã–π —Ö–ª–µ–±, –±–∞–≥–µ—Ç—ã, –±—É–ª–æ—á–∫–∏, —á–∏–∞–±–∞—Ç—Ç–∞, —Å—ç–Ω–¥–≤–∏—á–∏, –±–∞–≥–µ—Ç—ã –¥–ª—è —Å—ç–Ω–¥–≤–∏—á–µ–π, –±—É–ª–æ—á–∫–∏ –¥–ª—è –≥–∞–º–±—É—Ä–≥–µ—Ä–æ–≤, —Å–≤–µ–∂–∞—è –≤—ã–ø–µ—á–∫–∞, —Å–ª–æ–π–∫–∏, –∫—Ä—É–∞—Å—Å–∞–Ω—ã, –º–∞—Ñ—Ñ–∏–Ω—ã, –≤–∫—É—Å–Ω—ã–µ —Ç–æ—Ä—Ç—ã, —Å–∞–ª–∞—Ç—ã, –∫–æ–º–ø–ª–µ–∫—Å–Ω—ã–µ –æ–±–µ–¥—ã –¥–ª—è –∫–∞—Ñ–µ, –∫–æ—Ñ–µ–π–Ω–∏, –±–∏—Å—Ç—Ä–æ, —Å—Ç–æ–ª–æ–≤–æ–π, —Ä–µ—Å—Ç–æ—Ä–∞–Ω–∞."
		subdescription = "–¶–µ–Ω—ã –ø—Ä–æ–∏–∑–≤–æ–¥–∏—Ç–µ–ª—è <br>–û–ø—Ç –∏ –ú–µ–ª–∫–∏–π –æ–ø—Ç –æ—Ç 35—Ä—É–±. <br>–í—ã–≥–æ–¥–Ω—ã–µ –∏–Ω–¥–∏–≤–∏–¥—É–∞–ª—å–Ω—ã–µ —É—Å–ª–æ–≤–∏—è <br>–ö–∞—á–µ—Å—Ç–≤–æ, –ø–æ–¥—Ç–≤–µ—Ä–∂–¥—ë–Ω–Ω–æ–µ –î–µ–∫–ª–∞—Ä–∞—Ü–∏—è–º–∏ –ï–ê–≠–° <br>–ë—ã—Å—Ç—Ä–æ–µ –∏—Å–ø–æ–ª–Ω–µ–Ω–∏–µ –∑–∞—è–≤–∫–∏ –æ—Ç 1–¥–Ω—è! <br>–°–≤–µ–∂–∞—è –∏ –ó–∞–º–æ—Ä–æ–∂–µ–Ω–Ω–∞—è –ø—Ä–æ–¥—É–∫—Ü–∏—è <br>–î–æ—Å—Ç–∞–≤–∫–∞ –ø–æ –ú–∏–Ω—Å–∫—É"
		productionButtonText = "–ù–∞—à–∞ –ø—Ä–æ–¥—É–∫—Ü–∏—è"
		productionButtonTitle = "–û–ø–∏—Å–∞–Ω–∏–µ –∏ —Å—Ç–æ–∏–º–æ—Å—Ç—å –ø—Ä–æ–¥—É–∫—Ü–∏–∏: –°—ç–Ω–¥–≤–∏—á–∏, –í—ã–ø–µ—á–∫–∞, –¢–æ—Ä—Ç—ã, –ú–µ–ª–∫–∏–π –æ–ø—Ç | –•–∞—É—Å–§—Ä–µ—à –ú–∏–Ω—Å–∫"
		productionButtonLink = "/production/"

		
	# Partners section
	[params.partners]
		[[params.partners.list]]
		logo = "—Å–µ—Ç—å-–∫–æ—Ñ–µ–µ–Ω-–ü–µ—Ä—Å–ø–µ–∫—Ç–∏–≤–∞-–ú–∏–Ω—Å–∫-–ª–æ–≥–æ.jpg"
		alt = "–ü–µ—Ä—Å–ø–µ–∫—Ç–∏–≤–∞ –∫–æ—Ñ–µ –ª–æ–≥–æ—Ç–∏–ø"
		
		[[params.partners.list]]
		logo = "—Å–µ—Ç—å-–∫–∞—Ñ–µ-Yummy-–ú–∏–Ω—Å–∫-–ª–æ–≥–æ.svg"
		alt = "Yummy –∫–∞—Ñ–µ –ª–æ–≥–æ—Ç–∏–ø"
		
		[[params.partners.list]]
		logo = "—Å–µ—Ç—å-–∫–æ—Ñ–µ–µ–Ω-–Ω–∞-–∫–æ–ª—ë—Å–∞—Ö-Coffeecake-–ú–∏–Ω—Å–∫-–ª–æ–≥–æ.jpg"
		alt = "Coffeecake —Å–µ—Ç—å –∫–æ—Ñ–µ–µ–Ω –Ω–∞ –∫–æ–ª—ë—Å–∞—Ö –ª–æ–≥–æ—Ç–∏–ø"
		
		[[params.partners.list]]
		logo = "–±—É—Ñ–µ—Ç-–°–≤–µ–∂–∞–µ–∂–∞-–ú–∏–Ω—Å–∫-–ª–æ–≥–æ.jpg"
		alt = "–°–≤–µ–∂–∞–ï–∂–∞ –±—É—Ñ–µ—Ç –ª–æ–≥–æ—Ç–∏–ø"
		
		[[params.partners.list]]
		logo = "–∫–∞—Ñ–µ-–±–∏—Å—Ç—Ä–æ-–æ–±–µ–¥-–±—É—Ñ–µ—Ç-–ú–∏–Ω—Å–∫-–ª–æ–≥–æ.svg"
		alt = "–ö–∞—Ñ–µ-–±–∏—Å—Ç—Ä–æ '–û–±–µ–¥ –ë—É—Ñ–µ—Ç' –ú–∏–Ω—Å–∫ –ª–æ–≥–æ—Ç–∏–ø"
	    

	# Contact section
	[params.contact]
		address = "220014, –†–ë, –≥.–ú–∏–Ω—Å–∫, –ø—Ä–æ—Å–ø–µ–∫—Ç –ñ—É–∫–æ–≤–∞, –¥.44, –æ—Ñ–∏—Å 1-4"
		addressTitle = "–ü–æ–∫–∞–∑–∞—Ç—å –∞–¥—Ä–µ—Å –•–∞—É—Å–§—Ä–µ—à –Ω–∞ –∫–∞—Ä—Ç–µ"
		phone = "+375293728006"
		phone2 = "+375445148090"
		phoneTitle = "–ü–æ–∑–≤–æ–Ω–∏—Ç—å –≤ –æ—Ç–¥–µ–ª –ø—Ä–æ–¥–∞–∂ –ø—Ä–æ–¥—É–∫—Ç–æ–≤ –ø–∏—Ç–∞–Ω–∏—è –•–∞—É—Å–§—Ä–µ—à"
		phoneDescription ="+375 29 372 80 06"
		phoneDescription2 ="+375 44 514 80 90"
		orderEmail = "housefreshbysm@gmail.com"
		workingHours = "–±—É–¥–Ω–∏–µ –¥–Ω–∏ —Å 9.00 –¥–æ 18.00"
				
		companyIcon = "img/houseFreshLogo64x64.svg"	
		copyrightMain = "¬© –•–∞—É—Å–§—Ä–µ—à 2018 | –í—Å–µ –ø—Ä–∞–≤–∞ –∑–∞—â–∏—â–µ–Ω—ã."
		copyrightDescription = "–ö–æ–ø–∏—Ä–æ–≤–∞–Ω–∏–µ –∏ –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏–µ –º–∞—Ç–µ—Ä–∏–∞–ª–æ–≤ –¥–∞–Ω–Ω–æ–≥–æ —Å–∞–π—Ç–∞ —Ä–∞–∑—Ä–µ—à–µ–Ω–æ —Ç–æ–ª—å–∫–æ –ø–æ —Å–æ–≥–ª–∞—Å–æ–≤–∞–Ω–∏—é —Å –≤–ª–∞–¥–µ–ª—å—Ü–µ–º."