baseurl = "https://housefresh.by/"
languageCode = "en-us"
title = "Продукты питания, производство, дистрибуция, обеды | ХаусФреш"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "ХаусФреш"

	# The path must be relative to the static folder
	favicon = "img/houseFreshLogo.png"


	# Navigation
	[params.navigation]
		brand = "ХаусФреш"
		brandIcon = "img/houseFreshLogo.png"

		[params.navigation.links]
			about     = "О нас"
			services = "Услуги"
			partners  = "Партнёры"
			contact   = "Контакты"


	# Hero section
	[params.hero]
		slogan     = "ХАУСФРЕШ | продукты питания"
		companyIcon = "img/houseFreshLogo128x128.svg"	
		subtitle   = "[Мы предлагаем] (#services) оптовые и мелкооптовые поставки широкого ассортимента сэндвичей, фаршированных мини-багетов, свежей выпечки и кондитерских изделий собственного производства, а также профессиональную дистрибуцию продуктов питания и организацию обедов на предприятиях!"
		buttonText = "Наши услуги"


	# About section
	[params.about]
		headline    = "У нас есть то, что Вам нужно!"
		description = "Компания [ХаусФреш](#) существует на рынке продуктов питания совсем недавно, но уже успела завоевать популярность среди потребителей и зарекомендовать себя как надёжного партнёра. Мы нацелены на создание высококачественных продуктов питания, построение долгосрочных и надёжных отношений с нашими клиентами и партнёрами." 
		subdescription = "Мы - команда профессионалов в своём деле, мы молоды и динамичны, мы не стоим на месте, постоянно развиваемся и ищем новые пути решения наших задач. <br> Мы растём каждый день и готовы помочь нашим партнёрам расти вместе с нами! Мы приложим все усилия для эффективной совместной работы над общими целями. <br> Присоединяйтесь к нам!"
		buttonText = "Связаться"

			
	# services section
	[params.services]
		#headline    = "К вашим услугам"
		#description = "[ХаусФреш](/) предлагает ... "
	[params.services.downloadButton]
			text = "Скачать каталог"
			link = "/files/catalog.pdf"
	[params.services.contactButton]
			text = "Связаться"
			link = "/#contact"

	# ServiceTiles for product catalog
	  [params.ProdTile]
	    [[params.ProdTile.showcase]]
		  title = "Производство продукции"
		  subtitle = "Качество, подтверждённое Декларациями Евразийского экономического союза!"
		  image = "catalog/production-tile.jpg"
		  alt = "производство продуктов питания ХаусФреш Минск"
		  url = "production"
		  atitle = "производство продуктов питания, каталог продукции ХаусФреш"
	
	# ServiceTiles Section
	  [params.ServiceTiles]
		enable = true
		
		[[params.ServiceTiles.showcase]]
		  title = "Дистрибуция"
		  subtitle = ""
		  image = "catalog/distribution-tile.jpg"
		  alt = "дистрибуция продуктов питания ХаусФреш Беларусь"
		  url = "distribution"
		  atitle = "дистрибуция продуктов питания ХаусФреш Беларусь"
		  

		[[params.ServiceTiles.showcase]]
		  title = "Организация питания"
		  subtitle = ""
		  image = "catalog/canteen-tile.jpg"
		  alt = "организация питания на предприятиях Минска и Беларуси ХаусФреш"
		  url = "canteen"
		  atitle = "организация питания на предприятиях, доставка обедов в офис и бизнес-центры Минск"

		
    # Aside section
	[params.aside]
		headline = "Скачать каталог в формате PDF"

		[params.aside.button]
			text = "Скачать"
			link = "/files/catalog.pdf"
	
	
	# Partners section
	[params.partners]
		headline    = "Благодарим за плодотворное взаимовыгодное сотрудничество"
		description = " "
		
		[[params.partners.list]]
		logo = "yummy.svg"
		alt = "партнёр Yummy кафе логотип"
		#link = "#"
		
	    

	# Contact section
	[params.contact]
		headline = "Давайте оставаться на связи!"
		description = "Готовы к сотрудничеству? Отлично! <br> Просто позвоните нам или напишите письмо на электронную почту, и наши специалисты проконсультируют по любому вопросу, а также предложат самые выгодные индивидуальные условия!"
		address = "г.Минск, проспект Жукова, д.44, офис 1-4"
		phone = "+375 29 6089560 (Евгений)"
		email = "belov.evgen@mail.ru"
		text = "Время приёма звонков и обработки корреспонденции: с понедельника по пятницу 9:00-18:00. Суббота и воскресенье - выходные дни."
		
		companyIcon = "img/houseFreshLogo64x64.svg"	
		copyright = "© 2018 ХаусФреш, г.Минск, проспект Жукова, д.44, офис 1-4"
