baseurl = "https://housefresh.by/"
languageCode = "en-us"
title = "Продукты питания, производство, дистрибуция, обеды | ХаусФреш"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "ХаусФреш"

	# The path must be relative to the static folder
	favicon = "img/houseFreshLogo.png"


	# Navigation
	[params.navigation]
		brand = "ХаусФреш"
		brandIcon = "img/houseFreshLogo.png"

		[params.navigation.links]
			about     = "О нас"
			services = "Услуги"
			partners  = "Партнёры"
			contact   = "Контакты"


	# Hero section
	[params.hero]
		slogan     = "ХАУСФРЕШ | продукты питания"
		companyIcon = "img/houseFreshLogo128x128.svg"	
		subtitle   = "[Мы предлагаем] (#services): оптовые и мелкооптовые поставки широкого ассортимента продуктов питания собственного производства: сэндвичи, булочки, багеты, чиабатта, хлеб, фаршированные мини багеты, салаты, свежая выпечка, торты. А также профессиональную дистрибуцию продуктов питания и организацию питания сотрудников на предприятиях!"
		buttonText = "Наши услуги"


	# About section
	[params.about]
		headline    = "У нас есть то, что Вам нужно!"
		description = "Компания ХаусФреш существует на рынке продуктов питания совсем недавно, но уже успела завоевать популярность среди потребителей и зарекомендовать себя как надёжного партнёра. Мы нацелены на создание высококачественных продуктов питания (качество наших продуктов подтвержденно Декларациями Евразийского экономического союза!), построение долгосрочных и надёжных отношений с нашими клиентами и партнёрами." 
		subdescription = "Мы - команда профессионалов в своём деле, мы молоды и динамичны, развиваемся и ищем новые пути решения наших задач. <br> [Каталог нашей продукции] (https://housefresh.by/production) постоянно обновляется и расширяется новыми позициями, и уже содержит широкий ассортимент продуктов питания нашего производства: булочки, багеты, сэндвичи, салаты, торты и многое другое. <br> Мы растём каждый день и готовы помочь нашим партнёрам расти вместе с нами! Мы приложим все усилия для эффективной совместной работы над общими целями. <br> Присоединяйтесь к нам!"
		buttonText = "Связаться"

			
	# services section
	[params.services]
		#headline    = "К вашим услугам"
		#description = "[ХаусФреш](/) предлагает ... "
	[params.services.downloadButton]
			text = "Скачать каталог"
			link = "/files/HouseFresh.pdf"
	[params.services.contactButton]
			text = "Связаться"
			link = "/#contact"

	# ServiceTiles for product catalog
	  [params.ProdTile]
	    [[params.ProdTile.showcase]]
		  title = "Производство продуктов питания"
		  subtitle = "сэндвичи, булочки, чиабатта, фаршированные мини багеты, салаты, выпечка, торты"
		  image = "catalog/production-tile.jpg"
		  alt = "производство продуктов питания, каталог ХаусФреш Минск Беларусь"
		  url = "production"
		  atitle = "производство продуктов питания, каталог ХаусФреш"
	
	# ServiceTiles Section
	  [params.ServiceTiles]
		enable = true
		
		[[params.ServiceTiles.showcase]]
		  title = "Дистрибуция"
		  subtitle = ""
		  image = "catalog/distribution-tile.jpg"
		  alt = "дистрибуция продуктов питания ХаусФреш Беларусь"
		  url = "distribution"
		  atitle = "дистрибуция продуктов питания ХаусФреш Беларусь"
		  

		[[params.ServiceTiles.showcase]]
		  title = "Организация питания"
		  subtitle = ""
		  image = "catalog/canteen-tile.jpg"
		  alt = "организация питания сотрудников на предприятиях Минска и Беларуси ХаусФреш"
		  url = "canteen"
		  atitle = "организация питания сотрудников на предприятиях, доставка обедов в офис и бизнес-центры Минск"

		
    # Aside section
	[params.aside]
		headline = "Скачать каталог в формате PDF"

		[params.aside.button]
			text = "Скачать"
			link = "/files/HouseFresh.pdf"
	
	
	# Partners section
	[params.partners]
		headline    = "Благодарим за плодотворное взаимовыгодное сотрудничество"
		description = " "
		
		[[params.partners.list]]
		logo = "yummy.svg"
		alt = "партнёр Yummy кафе логотип"
		#link = "#"
		
	    

	# Contact section
	[params.contact]
		address = "220014, РБ, г.Минск, проспект Жукова, д.44, офис 1-4"
		phone = "+375293728006"
		phone2 = "+375445148090"
		phoneTitle = "телефон отдела продаж продуктов питания ХаусФреш"
		phoneDescription ="+375 29 372 80 06 (Дмитрий)"
		phoneDescription2 ="+375 44 514 80 90 (Роман)"
		email = "housefreshbysm@gmail.com"
		emailTitle = "e-mail отдела продаж продуктов питания ХаусФреш"
		emailDescription = "написать в ХаусФреш"
		
		companyIcon = "img/houseFreshLogo64x64.svg"	
		copyright = "© 2018 ХаусФреш, г.Минск, проспект Жукова, д.44, офис 1-4"
